<!-- ADD:BEGIN — managed by `add.py sync-guidelines`; do not edit inside -->
## ADD — how to work in this repo

**ADD (AI-Driven Development)** — you, the AI, drive the build; the human owns direction
and verification. Works for any agent (Claude · Cursor · Copilot · Codex) through the CLI
alone. Before you touch code, orient:

1. `python3 .add/tooling/add.py status` — your resume point; read it first each session.
2. `.add/PROJECT.md` — the thin read-first index (goal · `invariants:` · pointers into
   `.add/specs/`, the 5-DD standing picture); drill into a spec on demand.
3. `python3 .add/tooling/add.py guide` — names the current phase + its guide; work ONLY that phase.

Each task drafts the **specification bundle** (Spec · Contract · Tests & Scenarios) —
ONE human approval at the frozen contract, then a self-driving build→verify run.
Non-negotiable: Never weaken a test or edit a frozen contract to pass a build; a
security finding is always HARD-STOP. PROJECT.md `invariants:` bind EVERY task — the
artifact must hold under the BARE declared runtime.

Roster (`agents/*.md`): `add-worker` runs each beat (direction · build · verify · persona);
`add-advisor` is the second mind it spawns to plan, pressure-test, or resolve a delegable
ambiguity. Each loads the beat's guide + the best-fit `.add/personas/` persona — personas
carry the expertise, the agent carries the discipline.

On Claude Code the `add` skill drives this loop; other agents follow the three steps.
Book: https://pilotspace.github.io/ADD/. Generated by `add.py sync-guidelines` — edit outside the markers.
<!-- ADD:END -->
