"""Regression: the /v1/files body-size cap boundary (files-uploads-api PLAN.md §3).

Earned-green refute (2026-07-24): the OUTER BodySizeLimitMiddleware maps "/v1/" ->
max_json_body_bytes (20 MiB) as its longest-prefix default, so before the fix /v1/files
inherited that 20 MiB cap even though files_max_bytes is 512 MiB. Every upload in the
20 MiB -> files_max_bytes range was therefore rejected 413 ERR_REQUEST_BODY_TOO_LARGE and
the CONTRACTED 413 ERR_FILE_TOO_LARGE (§3 Reject) could never fire for that whole range —
and the frozen suite only ever probed tiny fixtures, so it never caught it.

These tests pin the boundary with a SECOND app built with tiny caps (outer JSON cap 1 KiB,
per-file cap 8 KiB) so the realistic "above the outer /v1/ cap, below files_max_bytes"
window is exercised with KiB-sized generated bytes (no giant literals, fast):

  - a file ABOVE the outer /v1/ JSON cap but BELOW files_max_bytes -> 200 (the dedicated
    /v1/files route cap overrides the wider /v1/ cap). WITHOUT the fix this is a 413
    ERR_REQUEST_BODY_TOO_LARGE.
  - a file ABOVE files_max_bytes -> the contracted 413 ERR_FILE_TOO_LARGE, emitted by the
    ROUTER (not the outer guard) — proving the router owns the exact boundary because the
    outer cap carries a headroom above files_max_bytes.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any

import httpx
import pytest

from gateway.core.config import Settings
from gateway.core.db import Base
from gateway.main import create_app
from tests import _redis_env
from tests.credential_stub import install_stub_resolver

pytestmark = pytest.mark.asyncio


# Local copies of the frozen suite's helpers (kept local rather than imported so the frozen
# test module is never touched and no private symbol is imported across modules).
def _bearer(key: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {key}"}


async def _signup_and_key(
    client: httpx.AsyncClient, *, tenant_name: str, email: str, password: str
) -> dict[str, str]:
    signup = await client.post(
        "/admin/auth/signup",
        json={"tenant_name": tenant_name, "email": email, "password": password},
    )
    assert signup.status_code == 201, f"signup failed: {signup.text}"
    token = (
        await client.post("/admin/auth/login", json={"email": email, "password": password})
    ).json()["access_token"]
    created = await client.post(
        "/admin/keys",
        json={"name": f"ci-key-{tenant_name}"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert created.status_code == 201, f"key creation failed: {created.text}"
    return {"key": created.json()["key"]}


async def _upload(
    client: httpx.AsyncClient,
    key: str,
    *,
    filename: str,
    data: bytes,
    purpose: str,
    content_type: str,
) -> httpx.Response:
    return await client.post(
        "/v1/files",
        files={"file": (filename, data, content_type)},
        data={"purpose": purpose},
        headers=_bearer(key),
    )

# Tiny caps so the realistic "above outer cap / below file cap" window is a few KiB.
_OUTER_JSON_CAP = 1024  # /v1/ + /admin/ JSON body cap
_FILE_CAP = 8192  # per-file cap (Settings.files_max_bytes)


@pytest.fixture
def capped_settings() -> Settings:
    return Settings(
        database_url=_redis_env.TEST_DATABASE_URL,
        jwt_secret="test-secret-not-for-production-0123456789",
        redis_url=_redis_env.TEST_REDIS_URL,
        public_signup_enabled=True,  # type: ignore[call-arg]
        max_json_body_bytes=_OUTER_JSON_CAP,  # type: ignore[call-arg]
        files_max_bytes=_FILE_CAP,  # type: ignore[call-arg]
    )


@pytest.fixture
async def capped_app(capped_settings: Settings) -> AsyncIterator[Any]:
    application = create_app(capped_settings)
    install_stub_resolver(application)
    engine = application.state.engine
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)
    yield application
    await engine.dispose()


@pytest.fixture
async def capped_client(capped_app: Any) -> AsyncIterator[httpx.AsyncClient]:
    transport = httpx.ASGITransport(app=capped_app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as c:
        yield c


class TestFilesBodyCapBoundary:
    async def test_upload_above_outer_json_cap_below_file_cap_succeeds(
        self, capped_client: httpx.AsyncClient
    ) -> None:
        """A file larger than the outer /v1/ JSON cap but smaller than files_max_bytes is
        accepted — /v1/files has its own (larger) body cap, it does not inherit /v1/'s."""
        keys = await _signup_and_key(
            capped_client,
            tenant_name="FilesCapA",
            email="files-cap-a@example.io",
            password="files-cap-a-battery",
        )
        # 2 KiB: > _OUTER_JSON_CAP (1 KiB) yet < _FILE_CAP (8 KiB). Before the fix the outer
        # /v1/ cap rejects this 413 ERR_REQUEST_BODY_TOO_LARGE.
        payload = b"x" * (2 * 1024)
        resp = await _upload(
            capped_client,
            keys["key"],
            filename="mid.bin",
            data=payload,
            purpose="user_data",
            content_type="application/octet-stream",
        )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert body["bytes"] == len(payload)
        assert body["id"].startswith("file-")

    async def test_upload_above_file_cap_is_contracted_413(
        self, capped_client: httpx.AsyncClient
    ) -> None:
        """A file above files_max_bytes returns the CONTRACTED 413 ERR_FILE_TOO_LARGE from
        the router — not the outer guard's ERR_REQUEST_BODY_TOO_LARGE — because the outer
        /v1/files cap carries a headroom above files_max_bytes so the router owns the edge."""
        keys = await _signup_and_key(
            capped_client,
            tenant_name="FilesCapB",
            email="files-cap-b@example.io",
            password="files-cap-b-battery",
        )
        # 9 KiB: > _FILE_CAP (8 KiB) but well under the outer /v1/files cap (8 KiB + 1 MiB
        # headroom), so it reaches the router, which emits the contracted code.
        payload = b"y" * (9 * 1024)
        resp = await _upload(
            capped_client,
            keys["key"],
            filename="big.bin",
            data=payload,
            purpose="user_data",
            content_type="application/octet-stream",
        )
        assert resp.status_code == 413, resp.text
        assert resp.json()["code"] == "ERR_FILE_TOO_LARGE"

    async def test_upload_at_file_cap_boundary_succeeds(
        self, capped_client: httpx.AsyncClient
    ) -> None:
        """Exactly files_max_bytes of raw file bytes is accepted (the reject is strictly
        greater-than) — the multipart framing overhead must NOT push a boundary file over
        the outer guard, which is what the headroom guarantees."""
        keys = await _signup_and_key(
            capped_client,
            tenant_name="FilesCapC",
            email="files-cap-c@example.io",
            password="files-cap-c-battery",
        )
        payload = b"z" * _FILE_CAP  # exactly the cap
        resp = await _upload(
            capped_client,
            keys["key"],
            filename="edge.bin",
            data=payload,
            purpose="user_data",
            content_type="application/octet-stream",
        )
        assert resp.status_code == 200, resp.text
        assert resp.json()["bytes"] == _FILE_CAP
