"""add_engine.guidelines — the guidelines / CLAUDE.md-injection subsystem (engine-modularization 8/N).

Inject one stable, marker-delimited ADD block into every GUIDELINE_FILES target under the
project root (AGENTS.md, CLAUDE.md, .clinerules). DYNAMIC-BY-REFERENCE: the block tells the
agent to run `add.py status` and read PROJECT.md — it never embeds live state. A closed,
self-contained cluster (4 fns + the cluster-private _INIT_EXCLUDE); transitive-closure AST
scan: ZERO outbound calls to non-cluster add fns. Deps: constants + _atomic_write (io_state)
+ stdlib. None patched.
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

from add_engine.constants import (
    GUIDELINE_FILES,
    SPEC_DDS,
    _GUIDE_BEGIN,
    _GUIDE_END,
    _SPECS_BEGIN,
    _SPECS_END,
)
from add_engine.io_state import _atomic_write


def _guideline_block() -> str:
    """The canonical ADD block (markers + body, no trailing newline).

    Agent-agnostic by design (v14 agent-portability): the routing steps depend
    only on the CLI and plain files, so any agent — Claude, Cursor, Copilot,
    Codex — can follow them. Claude additionally gets the `add` skill."""
    return (
        f"{_GUIDE_BEGIN}\n"
        "## ADD — how to work in this repo\n"
        "\n"
        "**ADD (AI-Driven Development)** — you, the AI, drive the build; the human owns direction\n"
        "and verification. Works for any agent (Claude · Cursor · Copilot · Codex) through the CLI\n"
        "alone. Before you touch code, orient:\n"
        "\n"
        "1. `python3 .add/tooling/add.py status` — your resume point; read it first each session.\n"
        "2. `.add/PROJECT.md` — the thin read-first index (goal · `invariants:` · pointers into\n"
        "   `.add/specs/`, the 5-DD standing picture); drill into a spec on demand.\n"
        "3. `python3 .add/tooling/add.py guide` — names the current phase + its guide; work ONLY that phase.\n"
        "\n"
        "Each task drafts the **specification bundle** (Spec · Contract · Tests & Scenarios) —\n"
        "ONE human approval at the frozen contract, then a self-driving build→verify run.\n"
        "Non-negotiable: Never weaken a test or edit a frozen contract to pass a build; a\n"
        "security finding is always HARD-STOP. PROJECT.md `invariants:` bind EVERY task — the\n"
        "artifact must hold under the BARE declared runtime.\n"
        "\n"
        "Roster (`agents/*.md`): `add-worker` runs each beat (direction · build · verify · persona);\n"
        "`add-advisor` is the second mind it spawns to plan, pressure-test, or resolve a delegable\n"
        "ambiguity. Each loads the beat's guide + the best-fit `.add/personas/` persona — personas\n"
        "carry the expertise, the agent carries the discipline.\n"
        "\n"
        "On Claude Code the `add` skill drives this loop; other agents follow the three steps.\n"
        "Book: https://pilotspace.github.io/ADD/. Generated by `add.py sync-guidelines` — edit outside the markers.\n"
        f"{_GUIDE_END}"
    )


def _inject_block(path: Path) -> str:
    """Write the ADD block into `path`. Returns created|updated|unchanged.

    - unchanged: on-disk block already matches -> no write, no .bak (idempotent).
    - updated:   existing content changes -> back up the original to <path>.bak first.
    - created:   file did not exist -> write the block, no .bak.
    User content outside the markers is always preserved.
    """
    block = _guideline_block()
    if path.exists():
        current = path.read_text(encoding="utf-8")
        begin = current.find(_GUIDE_BEGIN)
        if begin != -1:
            end = current.find(_GUIDE_END, begin)
            if end != -1:                      # replace only the marked region
                end += len(_GUIDE_END)
                new = current[:begin] + block + current[end:]
            else:                              # begin without end: corrupt — append fresh
                print(f"add: warning: {path.name}: found an ADD:BEGIN with no ADD:END "
                      "— appending a fresh block; review the result", file=sys.stderr)
                new = current.rstrip("\n") + "\n\n" + block + "\n"
        else:                                  # no block yet — append, keep user content
            new = current.rstrip("\n") + "\n\n" + block + "\n"
        if new == current:
            return "unchanged"
        _atomic_write(Path(str(path) + ".bak"), current)   # rollback path before mutate
        _atomic_write(path, new)
        return "updated"
    _atomic_write(path, block + "\n")
    return "created"


def _inject_guidelines(project_root: Path) -> list[tuple[str, str]]:
    """Inject the block into each guideline file under `project_root`.

    Symlink-dedup: targets resolving (os.path.realpath) to the same inode are
    written once, against the REAL file (never replacing the symlink with a
    regular file). Per-target OSError is isolated (warn+skip) so one unwritable
    file never aborts the run or `init`.
    """
    results: list[tuple[str, str]] = []
    seen: set[str] = set()
    for name in GUIDELINE_FILES:
        target = project_root / name
        real = os.path.realpath(target)
        if real in seen:
            continue
        seen.add(real)
        write_target = Path(real) if target.is_symlink() else target
        try:
            action = _inject_block(write_target)
        except (OSError, UnicodeDecodeError) as exc:
            # design for failure: an unwritable target OR a non-UTF-8 existing file
            # (e.g. a UTF-16 CLAUDE.md from a Windows editor) must not crash init or
            # abort the other target — warn and skip this one.
            print(f"add: warning: could not sync {name} — {exc}; skipped",
                  file=sys.stderr)
            action = "skipped"
        results.append((name, action))
    return results


# --- PROJECT.md specs pointers -----------------------------------------------

def _specs_pointer_block() -> str:
    """The managed ADD:SPECS block (markers + body), driven entirely by SPEC_DDS.

    PROJECT.md is the thin read-first index; this block routes to the standing
    5-DD picture in `.add/specs/` — one line per lens, so the picture can never
    drift from the closed 5-DD map."""
    lines = [
        _SPECS_BEGIN,
        "## Foundation specs — the standing 5-DD picture",
        "",
        "This file is the thin index; the detail lives in the specs. Lessons land there via "
        "`add.py delta-append <dd>`.",
        "",
    ]
    for _dd, (fname, title, lens) in SPEC_DDS.items():
        lines.append(f"- **{title}** → `.add/specs/{fname}` — {lens}")
    lines.append(_SPECS_END)
    return "\n".join(lines)


def _inject_specs_pointers(project_md: Path) -> str:
    """Inject/refresh the ADD:SPECS pointer block in PROJECT.md. Idempotent.

    Returns created|updated|unchanged|absent:
    - absent:    PROJECT.md does not exist -> no-op (nothing to wire).
    - unchanged: on-disk block already matches -> no write.
    - updated:   markers present -> replace only the marked region (refresh).
    - created:   markers absent  -> insert before the first '## ' section
                 (keeping the header/goal above it); append if no section exists.
    Content outside the markers is always preserved."""
    if not project_md.exists():
        return "absent"
    current = project_md.read_text(encoding="utf-8")
    block = _specs_pointer_block()
    begin = current.find(_SPECS_BEGIN)
    if begin != -1:
        end = current.find(_SPECS_END, begin)
        if end != -1:                          # replace only the marked region
            end += len(_SPECS_END)
            new = current[:begin] + block + current[end:]
        else:                                  # begin without end: corrupt — append fresh
            print(f"add: warning: {project_md.name}: found an ADD:SPECS with no close "
                  "— appending a fresh block; review the result", file=sys.stderr)
            new = current.rstrip("\n") + "\n\n" + block + "\n"
        action = "updated"
    else:                                      # no block yet — insert above the first section
        m = re.search(r"(?m)^## ", current)
        if m:
            new = current[:m.start()] + block + "\n\n" + current[m.start():]
        else:
            new = current.rstrip("\n") + "\n\n" + block + "\n"
        action = "created"
    if new == current:
        return "unchanged"
    _atomic_write(project_md, new)
    return action


# --- commands ----------------------------------------------------------------

_INIT_EXCLUDE = {
    ".add", "AGENTS.md", "CLAUDE.md", ".clinerules", ".git",
    ".gitignore", ".gitattributes", ".github", ".editorconfig",  # VCS/CI/editor scaffolding — no domain signal
    "LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING",            # legal boilerplate — no domain signal
}  # README/docs/source are NOT excluded: they carry domain content adopt.md maps -> brownfield


def _is_brownfield(base: Path) -> bool:
    """True when `base` already holds project content beyond the tool's own scaffolding.

    Judgment-free: a mechanical fact (does the dir hold a non-excluded entry?), so the
    autonomous-onboarding flow knows to map existing code into the living documentation. INTERPRETING
    that code stays with the AI (skill/add/adopt.md) — the engine only detects + signals."""
    if not base.is_dir():
        return False
    return any(child.name not in _INIT_EXCLUDE for child in base.iterdir())
