"""Red suite — e2e TLS termination tests (contract §3, edge-tls TASK.md).

Layer: @pytest.mark.e2e — requires the infra/docker-compose.e2e.yml stack to be running
with TLS certs generated by scripts/gen_dev_certs.sh.
Excluded from the default pytest run via pyproject.toml addopts: -m "not e2e".

Run by scripts/e2e_edge.sh (extended for TLS) or manually:
  uv run pytest tests/edge/test_e2e_tls.py -m e2e -q --no-cov

These tests are RED-BY-ABSENCE when the stack lacks TLS:
  - The :8443 port is not bound   -> httpx.ConnectError
  - No TLS certs exist            -> FileNotFoundError on CA cert load
  - envoy.yaml has no TLS listener-> httpx.ConnectError or SSL handshake failure

All TLS tests hit https://localhost:8443 (Envoy TLS listener) — NOT the gateway directly.
Existing :8080 tests in test_e2e_edge.py are NOT modified or duplicated here.

Configuration via environment variables:
  E2E_BASE_URL    — HTTP base URL (default: http://localhost:8080)
  E2E_TLS_URL     — HTTPS base URL (default: https://localhost:8443)
  E2E_CA_CERT     — path to dev CA cert for TLS verification
                    (default: infra/envoy/certs/dev-ca.pem, relative to repo root)
  GATEWAY_JWT_SECRET — shared JWT secret (default: e2e-test-secret-change-me)
  E2E_PROD_STACK  — set to "1" to enable S8 production-redirect test (requires
                    docker-compose.prod.yml stack running separately on 8080/8443)

IMPORTANT: Do NOT mark individual tests with skip — they must FAIL (not skip) when the
stack is not present. The e2e script is responsible for ensuring the stack is up before
running these tests. The sole exception is test_http_redirects_to_https_prod_topology
which requires a separate prod stack and is explicitly conditional-skip guarded.
"""

import os
import socket
import ssl
import uuid
from pathlib import Path
from typing import Any

import httpx
import pytest

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Repo root: two levels up from tests/edge/
_REPO_ROOT = Path(__file__).resolve().parents[4]

E2E_BASE_URL: str = os.environ.get("E2E_BASE_URL", "http://localhost:8080")
E2E_TLS_URL: str = os.environ.get("E2E_TLS_URL", "https://localhost:8443")

_DEFAULT_CA_CERT = str(_REPO_ROOT / "infra" / "envoy" / "certs" / "dev-ca.pem")
E2E_CA_CERT: str = os.environ.get("E2E_CA_CERT", _DEFAULT_CA_CERT)

E2E_JWT_SECRET: str = os.environ.get("GATEWAY_JWT_SECRET", "e2e-test-secret-change-me")

# Paths used by tests
HEALTH_PATH = "/health"
INTERNAL_AUTHZ_PATH = "/internal/authz"
SIGNUP_PATH = "/admin/auth/signup"
LOGIN_PATH = "/admin/auth/login"
ADMIN_KEYS_PATH = "/admin/keys"
V1_PATH = "/v1/chat/completions"

pytestmark = pytest.mark.e2e


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _tls_client(ca_cert: str = E2E_CA_CERT) -> httpx.AsyncClient:
    """Return an AsyncClient that verifies TLS against the dev CA cert.

    RED reason: if E2E_CA_CERT does not exist (certs not generated),
    httpx raises ssl.SSLError or FileNotFoundError on first use.
    """
    ssl_ctx = ssl.create_default_context(cafile=ca_cert)
    return httpx.AsyncClient(verify=ssl_ctx)


async def _https_signup_and_login(
    client: httpx.AsyncClient,
    *,
    tenant_name: str,
    email: str,
) -> str:
    """Sign up a fresh tenant over HTTPS :8443 and return a valid JWT."""
    password = "e2e-tls-correct-horse-battery"
    sr = await client.post(
        f"{E2E_TLS_URL}{SIGNUP_PATH}",
        json={"tenant_name": tenant_name, "email": email, "password": password},
        timeout=10.0,
    )
    assert sr.status_code == 201, (
        f"HTTPS signup failed (status {sr.status_code}): {sr.text}\n"
        "Check: is the TLS stack up? Did gen_dev_certs.sh run? Is :8443 exposed?"
    )
    lr = await client.post(
        f"{E2E_TLS_URL}{LOGIN_PATH}",
        json={"email": email, "password": password},
        timeout=10.0,
    )
    assert lr.status_code == 200, f"HTTPS login failed: {lr.text}"
    return lr.json()["access_token"]


async def _https_create_key(
    client: httpx.AsyncClient,
    jwt_token: str,
    name: str,
) -> dict[str, Any]:
    resp = await client.post(
        f"{E2E_TLS_URL}{ADMIN_KEYS_PATH}",
        json={"name": name},
        headers={"Authorization": f"Bearer {jwt_token}"},
        timeout=10.0,
    )
    assert resp.status_code == 201, (
        f"HTTPS key creation failed (status {resp.status_code}): {resp.text}"
    )
    return resp.json()


# ---------------------------------------------------------------------------
# S1 — TLS handshake succeeds; /health returns 200 over HTTPS
# ---------------------------------------------------------------------------


async def test_tls_handshake_health() -> None:
    """S1: TLS handshake with dev CA succeeds; /health returns 200.

    RED reason: :8443 is not bound (Envoy has no TLS listener) or
    E2E_CA_CERT does not exist (certs not generated by gen_dev_certs.sh).
    The failure mode is httpx.ConnectError or ssl.SSLError — not a wrong status code.
    """
    async with _tls_client() as client:
        resp = await client.get(f"{E2E_TLS_URL}{HEALTH_PATH}", timeout=5.0)

    assert resp.status_code == 200, (
        f"Expected 200 from gateway /health over HTTPS :8443, got {resp.status_code}: {resp.text}\n"
        "If you see a connection error above, the TLS listener is not configured.\n"
        "Run scripts/gen_dev_certs.sh and ensure :8443 is exposed in the e2e compose."
    )


# ---------------------------------------------------------------------------
# S2 — plain HTTP to :8443 is rejected at transport layer
# ---------------------------------------------------------------------------


async def test_plain_http_to_tls_port_rejected() -> None:
    """S2: A plain HTTP (non-TLS) request to :8443 must fail at transport layer.

    Envoy's TLS listener expects a TLS ClientHello; sending a plain HTTP request
    causes a TLS alert or TCP reset — httpx raises RemoteProtocolError or ConnectError.
    RED reason: if :8443 is not bound at all, we also get ConnectError (correct red).
    """
    with pytest.raises((httpx.RemoteProtocolError, httpx.ConnectError)):
        async with httpx.AsyncClient(verify=False) as client:  # noqa: S501
            # verify=False allows us to reach the port; but no TLS ClientHello is sent
            # because we use http:// scheme — httpx sends plain HTTP to a TLS port
            await client.get(
                f"http://localhost:8443{HEALTH_PATH}",
                timeout=5.0,
            )


# ---------------------------------------------------------------------------
# S3 — full HTTPS flow: signup → login → create key → /v1/ chat
# ---------------------------------------------------------------------------


async def test_https_full_flow_signup_key_v1() -> None:
    """S3: Full signup→login→key→/v1/ flow works identically over HTTPS :8443.

    We do NOT assert a 200 from /v1/ (gateway will fail upstream call without
    a real OpenRouter key). We assert Envoy did not reject the request (not 401/403
    from Envoy ext_authz — same assertion as S8 in test_e2e_edge.py).
    RED reason: :8443 TLS listener not configured; all requests fail at transport.
    """
    async with _tls_client() as client:
        jwt_token = await _https_signup_and_login(
            client,
            tenant_name=f"TLSFlowCo-{uuid.uuid4().hex[:6]}",
            email=f"tls-flow-{uuid.uuid4().hex[:6]}@e2e.io",
        )
        key_body = await _https_create_key(client, jwt_token, "tls-e2e-key")
        full_key: str = key_body["key"]

        resp = await client.post(
            f"{E2E_TLS_URL}{V1_PATH}",
            json={
                "model": "openai/gpt-3.5-turbo",
                "messages": [{"role": "user", "content": "ping"}],
            },
            headers={"Authorization": f"Bearer {full_key}"},
            timeout=10.0,
        )

    # ext_authz passed the request to the gateway when status is NOT 401/403 from Envoy
    assert resp.status_code not in (401, 403), (
        f"Envoy rejected the /v1/ request before reaching the gateway over HTTPS. "
        f"Status: {resp.status_code}, body: {resp.text[:500]!r}."
    )

    # Also confirm :8080 is still reachable (no regression on the HTTP listener)
    async with httpx.AsyncClient() as http_client:
        health = await http_client.get(f"{E2E_BASE_URL}{HEALTH_PATH}", timeout=5.0)
    assert health.status_code == 200, (
        f"HTTP :8080 /health regressed after TLS addition, got {health.status_code}"
    )


# ---------------------------------------------------------------------------
# S4a — HSTS header present on 200 responses from :8443
# ---------------------------------------------------------------------------


async def test_hsts_header_present_on_200() -> None:
    """S4a: Strict-Transport-Security header must be present on :8443 200 responses.

    RED reason: Envoy :8443 listener has no response_headers_to_add for HSTS,
    or :8443 is not bound at all.
    """
    async with _tls_client() as client:
        resp = await client.get(f"{E2E_TLS_URL}{HEALTH_PATH}", timeout=5.0)

    assert resp.status_code == 200, (
        f"Pre-condition failed: expected 200 from /health, got {resp.status_code}"
    )

    hsts = resp.headers.get("strict-transport-security", "")
    assert hsts, (
        f"Strict-Transport-Security header missing on HTTPS /health response.\n"
        f"All response headers: {dict(resp.headers)}"
    )

    # Extract max-age value and assert >= 2 years (63072000 seconds)
    max_age_part = next(
        (p.strip() for p in hsts.split(";") if p.strip().lower().startswith("max-age")),
        None,
    )
    assert max_age_part is not None, (
        f"Strict-Transport-Security header present but has no max-age directive: {hsts!r}"
    )
    max_age_value = int(max_age_part.split("=", 1)[1].strip())
    assert max_age_value >= 63072000, (
        f"HSTS max-age={max_age_value} is less than the required 63072000 (2 years): {hsts!r}"
    )


# ---------------------------------------------------------------------------
# S4b — HSTS header on 403 direct_response (xfail: known Envoy caveat)
# ---------------------------------------------------------------------------


@pytest.mark.xfail(
    reason=(
        "Envoy v1.29 listener-level response_headers_to_add may not apply to "
        "direct_response actions generated at the route level. If this test passes, "
        "the caveat is resolved and the xfail mark should be removed."
    ),
    strict=False,
)
async def test_hsts_header_on_403_direct_response() -> None:
    """S4b: HSTS header should be present even on 403 /internal/* direct responses.

    Marked xfail: Envoy's listener-level headers may not propagate to route-level
    direct_response or http_filter-generated responses. The test is written to assert
    the desired behavior; if Envoy does apply them, the test passes (xfail strict=False).
    See §3 contract ⚠ flag for full reasoning.
    RED reason: :8443 not bound, or HSTS not on direct_response path.
    """
    async with _tls_client() as client:
        resp = await client.get(
            f"{E2E_TLS_URL}{INTERNAL_AUTHZ_PATH}",
            timeout=5.0,
        )

    assert resp.status_code == 403, (
        f"Expected 403 for /internal/* on :8443, got {resp.status_code}: {resp.text}"
    )
    hsts = resp.headers.get("strict-transport-security", "")
    assert hsts, (
        f"HSTS header missing on 403 direct_response from :8443.\n"
        f"Response headers: {dict(resp.headers)}"
    )


# ---------------------------------------------------------------------------
# S5 — TLS version < 1.2 rejected at transport layer
# ---------------------------------------------------------------------------


async def test_tls_version_below_1_2_rejected() -> None:
    """S5: Attempting a TLS 1.1 (or 1.0) handshake to :8443 must be rejected.

    Envoy's tls_minimum_protocol_version: TLSv1_2 causes a handshake_failure alert
    for any client offering only TLS <= 1.1.
    RED reason: :8443 not bound, OR TLS minimum version not configured (allows 1.1).

    Note: Python's ssl module on modern systems may refuse to create a TLS 1.1 context
    at the OS level. We use PROTOCOL_TLS_CLIENT with OP_NO_TLSv1_2 + OP_NO_TLSv1_3
    to force the negotiation attempt. If the OS itself blocks it, the test is skipped
    with an informative message rather than failing (the security property is enforced
    at OS level, which is acceptable).
    """
    try:
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        # Force only TLS 1.0 / 1.1 by disabling 1.2 and 1.3
        ctx.options |= ssl.OP_NO_TLSv1_2
        ctx.options |= ssl.OP_NO_TLSv1_3
    except AttributeError:
        pytest.skip(
            "ssl.OP_NO_TLSv1_2 / OP_NO_TLSv1_3 not available on this platform — "
            "OS-level TLS 1.1 rejection is in effect; test skipped."
        )

    rejected = False
    try:
        with socket.create_connection(("localhost", 8443), timeout=5.0) as sock:
            with ctx.wrap_socket(sock, server_hostname="localhost"):
                pass  # handshake succeeded — this is the failure case
    except ssl.SSLError:
        rejected = True
    except OSError:
        # Port not bound — counts as a red failure for the right reason
        rejected = False

    assert rejected, (
        "TLS 1.1 handshake to :8443 succeeded — Envoy is NOT enforcing TLSv1_2 minimum. "
        "Set tls_minimum_protocol_version: TLSv1_2 in the DownstreamTlsContext."
    )


# ---------------------------------------------------------------------------
# S6 — existing HTTP :8080 listener still works (no regression)
# ---------------------------------------------------------------------------


async def test_http_8080_still_works_no_regression() -> None:
    """S6: The HTTP :8080 listener must remain functional alongside :8443.

    This is a guard test: TLS additions must not break the existing e2e stack.
    The full existing e2e suite (test_e2e_edge.py) is the definitive regression check;
    this test confirms at minimum that :8080 is up and the gateway responds.
    RED reason: if TLS changes accidentally disable :8080, this fails immediately.
    """
    async with httpx.AsyncClient() as client:
        resp = await client.get(f"{E2E_BASE_URL}{HEALTH_PATH}", timeout=5.0)

    assert resp.status_code == 200, (
        f"HTTP :8080 /health returned {resp.status_code} after TLS additions — regression detected.\n"
        f"Body: {resp.text}"
    )
    # Confirm no TLS-related headers leaked onto the HTTP listener (HSTS should NOT be
    # present on :8080 — it is a TLS-only header and its presence on HTTP is misleading)
    hsts = resp.headers.get("strict-transport-security", "")
    assert not hsts, (
        f"Strict-Transport-Security unexpectedly present on HTTP :8080 response: {hsts!r}\n"
        "HSTS should only be served on the :8443 TLS listener."
    )


# ---------------------------------------------------------------------------
# S7 — /internal/* blocked on :8443 (shared route_config)
# ---------------------------------------------------------------------------


async def test_internal_blocked_on_tls_listener() -> None:
    """S7: /internal/* must return 403 on :8443 (shared route_config with :8080).

    This validates that the route_config de-duplication (YAML anchor) correctly
    applies the /internal/* direct_response rule to the TLS listener.
    RED reason: :8443 not bound, OR route_config not shared (drift) — /internal/*
    may 404 or proxy to the gateway instead of returning 403.
    """
    async with _tls_client() as client:
        resp = await client.get(
            f"{E2E_TLS_URL}{INTERNAL_AUTHZ_PATH}",
            timeout=5.0,
        )

    assert resp.status_code == 403, (
        f"Expected 403 direct response for /internal/* on :8443, got {resp.status_code}.\n"
        f"Body: {resp.text!r}\n"
        "This means the route_config is not shared between :8080 and :8443 listeners, "
        "or the YAML anchor was not applied correctly — security gap: /internal/* is reachable via HTTPS."
    )


# ---------------------------------------------------------------------------
# S8 — :8080 redirects to HTTPS in production compose topology
# (conditional: requires E2E_PROD_STACK=1 and docker-compose.prod.yml running)
# ---------------------------------------------------------------------------


async def test_http_redirects_to_https_prod_topology() -> None:
    """S8: In production topology, HTTP :8080 issues a 301 redirect to HTTPS :8443.

    This test requires infra/docker-compose.prod.yml to be running separately.
    It is skipped unless E2E_PROD_STACK=1 is set in the environment.

    RED reason (when E2E_PROD_STACK=1): docker-compose.prod.yml does not exist yet
    (BUILD deliverable), so :8080 either returns 200 or is not bound.
    """
    if os.environ.get("E2E_PROD_STACK", "0") != "1":
        pytest.skip(
            "Production stack test skipped — set E2E_PROD_STACK=1 and start "
            "infra/docker-compose.prod.yml to run this test."
        )

    async with httpx.AsyncClient(follow_redirects=False) as client:
        resp = await client.get(
            f"http://localhost:8080{HEALTH_PATH}",
            timeout=5.0,
        )

    assert resp.status_code in (301, 302), (
        f"Expected redirect (301/302) from HTTP :8080 in production topology, "
        f"got {resp.status_code}: {resp.text!r}"
    )

    location = resp.headers.get("location", "")
    assert "https" in location.lower(), (
        f"Redirect Location header does not point to HTTPS: {location!r}"
    )
    assert "8443" in location or ":443" in location or (
        location.startswith("https://") and ":" not in location.split("//", 1)[1].split("/")[0]
    ), (
        f"Redirect Location does not include :8443 (or standard 443): {location!r}"
    )
